#!/usr/bin/env perl

use 5.008;

use strict;
use warnings;

use File::Spec;
use Getopt::Long 2.33 qw{ :config auto_version };
use Pod::Perldoc;
use Pod::Usage;

our $VERSION = '0.000_01';

my %opt;

GetOptions( \%opt,
    help => sub { pod2usage( { -verbose => 2 } ) },
) or pod2usage( { -verbose => 0 } );

my $pd = Pod::Perldoc->new();

{
    local *STDERR;
    open STDERR, '>', File::Spec->devnull();
    foreach ( $pd->grand_search_init( \@ARGV ) ) {
	print "$_\n";
    }
    close STDERR;
}

print STDERR "Testing -- STDERR still works\n";

__END__

=head1 TITLE

find-installed - <<< replace boiler plate >>>

=head1 SYNOPSIS

 find-installed
 find-installed -help
 find-installed -version

=head1 OPTIONS

<<< replace boiler plate >>>

=head2 -help

This option displays the documentation for this script. The script then
exits.

=head2 -version

This option displays the version of this script. The script then exits.

=head1 DETAILS

<<< replace boiler plate >>>

=head1 AUTHOR

Thomas R. Wyant, III F<wyant at cpan dot org>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2019 by Thomas R. Wyant, III

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl 5.10.0. For more details, see the full text
of the licenses in the directory LICENSES.

This program is distributed in the hope that it will be useful, but
without any warranty; without even the implied warranty of
merchantability or fitness for a particular purpose.

=cut

# ex: set textwidth=72 :
